import { HttpMethod } from './HttpMethod';

export type { HttpMethod };

export interface BaseResponseProviderConfig {
  statusCode: number;
  headers: Record<string, string>;
  injectLatencyMs?: number;
}

/** Config for a hard-coded response returned as-is. */
export interface StaticResponseProviderConfig extends BaseResponseProviderConfig {
  type: 'static';
  body: string;
}

/** Config for a response body generated by executing a JavaScript snippet. */
export interface ScriptResponseProviderConfig extends BaseResponseProviderConfig {
  type: 'script';
  /** JavaScript code that returns a JSON-serialisable value. */
  script: string;
}

/** Config for a response body rendered from a Mustache template. */
export interface TemplateResponseProviderConfig extends BaseResponseProviderConfig {
  type: 'template';
  template: string;
}

/** Config for proxying the request to one of the service's named environments. */
export interface ProxyResponseProviderConfig extends BaseResponseProviderConfig {
  type: 'proxy';
  /** Must match a ServiceEnvironment.name defined on the parent Service. */
  environment: string;
}

/** A single scenario within a ScenarioResponseProviderConfig. */
export interface Scenario {
  /** JavaScript function source text evaluated against the incoming request; first scenario returning true wins. */
  scenarioTestFnCallbackStr: string;
  response:
  | StaticResponseProviderConfig
  | ScriptResponseProviderConfig
  | TemplateResponseProviderConfig
  | ProxyResponseProviderConfig;
}

/** Config that evaluates scenarios in order and returns the response from the first match. */
export interface ScenarioResponseProviderConfig {
  type: 'scenario';
  scenarios: Scenario[];
}

export type ResponseProviderConfig =
  | StaticResponseProviderConfig
  | ScriptResponseProviderConfig
  | TemplateResponseProviderConfig
  | ProxyResponseProviderConfig
  | ScenarioResponseProviderConfig;

export interface Api {
  /** Must be unique within the parent Service. */
  name: string;
  description: string;
  method: HttpMethod;
  /** Regex matched against the incoming request URL path. */
  urlPattern: string;
  response: ResponseProviderConfig;
}
