import { HttpMethod } from './HttpMethod';

export type { HttpMethod };

export interface BaseResponseProviderConfig {
  statusCode: number;
  headers: Record<string, string>;
  injectLatencyMs?: number;
}

export interface MultipartResponsePart {
  contentType?: string;
  body: string;
}

/** Config for a hard-coded response returned as-is. */
export interface StaticResponseProviderConfig extends BaseResponseProviderConfig {
  type: 'static';
  body: string;
  /** When present and non-empty, the response is sent as multipart/form-data instead of using body. */
  multipartParts?: MultipartResponsePart[];
}

/** Config for a response body generated by executing a JavaScript snippet. */
export interface ScriptResponseProviderConfig extends BaseResponseProviderConfig {
  type: 'script';
  /** JavaScript code that returns a JSON-serialisable value. */
  script: string;
}

/** Config for a response body rendered from a Mustache template. */
export interface TemplateResponseProviderConfig extends BaseResponseProviderConfig {
  type: 'template';
  template: string;
}

/** Config for proxying the request to a downstream service. */
export interface ProxyResponseProviderConfig extends BaseResponseProviderConfig {
  type: 'proxy';
  /** Base URL of the downstream service (e.g. "https://api.example.com"). */
  targetUrl: string;
  /**
   * Optional JavaScript snippet to customise the outgoing request before forwarding.
   * Called with (request: MockRequest, outgoing: OutgoingRequest).
   * Mutate `outgoing.url`, `outgoing.query`, `outgoing.body`, or `outgoing.headers` as needed.
   */
  outgoingRequestBuilderScript?: string;
  /**
   * Optional JavaScript snippet to transform the downstream response before returning it.
   * Called with (request: MockRequest, response: { status: number; headers: Record<string,string>; body: unknown }).
   * Mutate `response` properties as needed.
   */
  responseBuilderScript?: string;
}

/** A single scenario within a ScenarioResponseProviderConfig. */
export interface Scenario {
  /** JavaScript function source text evaluated against the incoming request; first scenario returning true wins. */
  scenarioTestFnCallbackStr: string;
  response:
  | StaticResponseProviderConfig
  | ScriptResponseProviderConfig
  | TemplateResponseProviderConfig
  | ProxyResponseProviderConfig;
}

/** Config that evaluates scenarios in order and returns the response from the first match. */
export interface ScenarioResponseProviderConfig {
  type: 'scenario';
  scenarios: Scenario[];
}

export type ResponseProviderConfig =
  | StaticResponseProviderConfig
  | ScriptResponseProviderConfig
  | TemplateResponseProviderConfig
  | ProxyResponseProviderConfig
  | ScenarioResponseProviderConfig;

/** A JavaScript function body used to match incoming requests. */
export interface RequestMatcherFunction {
  /** JavaScript function body. Receives `request: MockRequest`, returns `boolean`. Empty = catch-all. */
  body: string;
}

/**
 * A conditional response provider.
 * `matcher.body` is a JavaScript function body (receives `request: MockRequest`, must return boolean).
 * An empty body is treated as a catch-all (always matches).
 * Providers are evaluated in order; the first match wins.
 */
export interface MockProviderConfig {
  /** Human-readable label. Must be unique within the parent Api's providers list. */
  name: string;
  matcher: RequestMatcherFunction;
  provider: ResponseProviderConfig;
  /** When false this provider is skipped during request matching. Defaults to true when absent. */
  enabled?: boolean;
  /** Scenario IDs this provider is associated with. Empty/undefined = applies to all scenarios. */
  scenarioIds?: string[];
}

export interface Api {
  /** Must be unique within the parent Service. */
  name: string;
  description: string;
  method: HttpMethod;
  /** Regex matched against the incoming request URL path. */
  urlPattern: string;
  /** Ordered list of conditional providers. First matching provider's response is used. */
  providers: MockProviderConfig[];
  /** When false this API is skipped by the mock router. Defaults to true when absent. */
  enabled?: boolean;
}
